// @tradrl/marketplace-service — the lane's single import surface.
//
// Work Order T047. One module owning every cross-module import so the
// frozen workspace lockfile story stays legible (the firm-memory and
// body-forge precedent): the service imports ITS OWN LANE's contract
// package — packages/entitlements — via a relative source path, exactly
// as services/firm-memory imports packages/firm-memory and
// services/body-forge imports packages/skills. Every OTHER lane's
// shapes (T045's provider exchange, T017's capability language, T041's
// API/SDK surface) are STRUCTURAL MIRRORS inside this service
// (law D-003/D-004); this lane imports NOTHING else — zero workspace
// dependencies in package.json, zero cross-lane source imports in src.
// Cross-lane trip wires against the REAL lanes (capability-provider,
// skills, sdk, api, body-forge) live in interop.test.ts (test-only
// imports).

// --- The contract package (@tradrl/entitlements, T047) ----------------------
export type {
  EntitlementErrorCode,
  EntitlementError,
  EntitlementResult,
  Brand,
  JsonValue,
  JsonObject,
  TimestampMs,
  EntitlementGrantId,
  ConsumptionRecordId,
  EntitlementRevocationId,
  TenantId,
  ProjectId,
  ArtifactRef,
  EntitlementKind,
  SpendAllowanceTerms,
  ApiQuotaTerms,
  LicenseUsageScope,
  ArtifactLicenseTerms,
  EntitlementTerms,
  EntitlementGrant,
  EntitlementGrantDraft,
  GrantWindowStatus,
  ConsumptionCause,
  ConsumptionRecord,
  ConsumptionDraft,
  GrantRevocation,
  EntitlementLedgerState,
  EntitlementLedgerView,
  LedgerOperationResult,
  EntitlementSnapshotEntry,
  EntitlementSnapshot,
  UsageRecordMirror,
  UsageQuotaVerdict,
  QuotaGrantView,
  SdkErrorFamilyMirror,
} from '../../../packages/entitlements/src/index';
export {
  ENTITLEMENT_ERROR_CODES,
  API_BOUNDARY_ERROR_FAMILY_OF as ENTITLEMENTS_API_BOUNDARY_ERROR_FAMILY_OF,
  isEntitlementErrorCode,
  fail as entitlementFail,
  failures as entitlementFailures,
  ok as entitlementOk,
  isRecord,
  isNonEmptyString,
  isFiniteNumber,
  isNonNegativeInteger,
  isPositiveInteger,
  isMemberOf,
  isArrayOf,
  deepFreeze,
  isDeeplyFrozen,
  deepCloneJson,
  isJsonValue,
  isJsonObject,
  canonicalJson,
  stableDigest,
  stableDigestJson,
  isDigest,
  fnv1a32Hex,
  MIN_TIMESTAMP_MS,
  MAX_TIMESTAMP_MS,
  isTimestampMs,
  timestampMs,
  UNSIGNED_DECIMAL_PATTERN,
  SIGNED_DECIMAL_PATTERN,
  isCanonicalUnsignedDecimal,
  isCanonicalSignedDecimal,
  isPositiveDecimal,
  isZeroDecimal,
  signedAdd,
  signedSubtract,
  signedNegate,
  signedAbs,
  signedCompare,
  unsignedAdd,
  unsignedSubtract,
  decimalMultiply,
  ENTITLEMENT_ID_PATTERN,
  isEntitlementGrantId,
  isConsumptionRecordId,
  isEntitlementRevocationId,
  isTenantId,
  isProjectId,
  isArtifactRef,
  deriveEntitlementGrantId,
  deriveConsumptionRecordId,
  deriveEntitlementRevocationId,
  chainHeadOf as entitlementChainHeadOf,
  ENTITLEMENT_KINDS,
  LICENSE_USAGE_SCOPES,
  isEntitlementKind,
  isLicenseUsageScope,
  isSpendAllowanceTerms,
  isApiQuotaTerms,
  isArtifactLicenseTerms,
  isEntitlementTerms,
  isEntitlementGrant,
  validateEntitlementGrant,
  grantIdentityContent,
  createEntitlementGrant,
  amendEntitlementGrant,
  grantWindowStatus,
  CONSUMPTION_CAUSES,
  ENTITLEMENT_LOG_KINDS,
  GENESIS_CHAIN_HEAD as ENTITLEMENTS_GENESIS_CHAIN_HEAD,
  isConsumptionCause,
  isConsumptionRecord,
  isGrantRevocation,
  createEntitlementLedger,
  verifyEntitlementChain,
  entitlementLedgerView,
  serializeEntitlementLedger,
  entitlementLedgerDigest,
  currentGrantOf,
  rootIdOf,
  issueEntitlementGrant,
  amendEntitlementGrantOn,
  revokeEntitlementGrant,
  consumeEntitlement,
  entitlementSnapshot,
  activeQuotaGrants,
  coveringSpendGrants,
  SDK_ERROR_FAMILIES_MIRROR,
  isSdkErrorFamilyMirror,
} from '../../../packages/entitlements/src/index';
